export interface StudentDiscountCatalogEntry {
  serviceId: string;
  serviceName: string;
  aliases: string[];
  regularPriceMonthly: number;
  studentPriceMonthly: number;
  currency: string;
  region: string;
  verificationMethod: string;
  offerUrl: string;
  lastChecked: string;
  isActive: boolean;
}

// Seed catalog for MVP development. Keep separate from production-managed offer data.
export const STUDENT_DISCOUNT_CATALOG_SEED: StudentDiscountCatalogEntry[] = [
  {
    serviceId: "spotify-us",
    serviceName: "Spotify Premium",
    aliases: ["spotify", "spotify usa"],
    regularPriceMonthly: 11.99,
    studentPriceMonthly: 5.99,
    currency: "USD",
    region: "US",
    verificationMethod: "SheerID",
    offerUrl: "https://www.spotify.com/us/student/",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "apple-music-us",
    serviceName: "Apple Music",
    aliases: ["apple music", "apple com bill", "apple bill", "apple services"],
    regularPriceMonthly: 10.99,
    studentPriceMonthly: 5.99,
    currency: "USD",
    region: "US",
    verificationMethod: "UNiDAYS",
    offerUrl: "https://www.apple.com/apple-music/",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "youtube-premium-us",
    serviceName: "YouTube Premium",
    aliases: ["youtube premium", "google youtube", "google youtube premium", "youtube"],
    regularPriceMonthly: 13.99,
    studentPriceMonthly: 7.99,
    currency: "USD",
    region: "US",
    verificationMethod: "SheerID",
    offerUrl: "https://www.youtube.com/premium/student",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "notion-us",
    serviceName: "Notion Plus",
    aliases: ["notion", "notion labs"],
    regularPriceMonthly: 10,
    studentPriceMonthly: 0,
    currency: "USD",
    region: "US",
    verificationMethod: "Student email",
    offerUrl: "https://www.notion.com/product/notion-for-education",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "canva-us",
    serviceName: "Canva Pro",
    aliases: ["canva", "canva pty", "canva com"],
    regularPriceMonthly: 14.99,
    studentPriceMonthly: 0,
    currency: "USD",
    region: "US",
    verificationMethod: "Education verification",
    offerUrl: "https://www.canva.com/education/students/",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "adobe-us",
    serviceName: "Adobe Creative Cloud",
    aliases: ["adobe", "adobe inc", "adobe creative cloud"],
    regularPriceMonthly: 59.99,
    studentPriceMonthly: 19.99,
    currency: "USD",
    region: "US",
    verificationMethod: "Student verification",
    offerUrl: "https://www.adobe.com/creativecloud/buy/students.html",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "amazon-prime-student-us",
    serviceName: "Amazon Prime",
    aliases: ["amazon prime", "amzn prime", "prime video", "amazon digital"],
    regularPriceMonthly: 14.99,
    studentPriceMonthly: 7.49,
    currency: "USD",
    region: "US",
    verificationMethod: "Student email",
    offerUrl: "https://www.amazon.com/prime/student",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "hulu-us",
    serviceName: "Hulu",
    aliases: ["hulu", "hulu with ads"],
    regularPriceMonthly: 11.99,
    studentPriceMonthly: 1.99,
    currency: "USD",
    region: "US",
    verificationMethod: "SheerID",
    offerUrl: "https://www.hulu.com/student",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "max-us",
    serviceName: "Max",
    aliases: ["max", "hbo max", "max basic with ads"],
    regularPriceMonthly: 9.99,
    studentPriceMonthly: 4.99,
    currency: "USD",
    region: "US",
    verificationMethod: "UNiDAYS",
    offerUrl: "https://help.max.com/US/Answer/Detail/000002583",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "github-copilot-us",
    serviceName: "GitHub Copilot Pro",
    aliases: ["github copilot", "copilot", "github", "github inc"],
    regularPriceMonthly: 10,
    studentPriceMonthly: 0,
    currency: "USD",
    region: "US",
    verificationMethod: "GitHub Education verification",
    offerUrl: "https://github.com/features/copilot/plans",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "microsoft-365-us",
    serviceName: "Microsoft 365 Personal",
    aliases: ["microsoft 365", "office 365", "office 365 personal", "microsoft", "msft"],
    regularPriceMonthly: 9.99,
    studentPriceMonthly: 0,
    currency: "USD",
    region: "US",
    verificationMethod: "Eligible school email",
    offerUrl: "https://www.microsoft.com/en-us/education/products/office",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "spotify-ca",
    serviceName: "Spotify Premium",
    aliases: ["spotify", "spotify usa"],
    regularPriceMonthly: 11.99,
    studentPriceMonthly: 5.99,
    currency: "CAD",
    region: "CA",
    verificationMethod: "SheerID",
    offerUrl: "https://www.spotify.com/ca-en/student/",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "apple-music-ca",
    serviceName: "Apple Music",
    aliases: ["apple music", "apple com bill", "apple bill", "apple services"],
    regularPriceMonthly: 10.99,
    studentPriceMonthly: 5.99,
    currency: "CAD",
    region: "CA",
    verificationMethod: "UNiDAYS",
    offerUrl: "https://www.apple.com/ca/apple-music/",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "youtube-premium-ca",
    serviceName: "YouTube Premium",
    aliases: ["youtube premium", "google youtube", "google youtube premium", "youtube"],
    regularPriceMonthly: 12.99,
    studentPriceMonthly: 7.99,
    currency: "CAD",
    region: "CA",
    verificationMethod: "SheerID",
    offerUrl: "https://www.youtube.com/premium/student",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "notion-ca",
    serviceName: "Notion Plus",
    aliases: ["notion", "notion labs"],
    regularPriceMonthly: 10,
    studentPriceMonthly: 0,
    currency: "CAD",
    region: "CA",
    verificationMethod: "Student email",
    offerUrl: "https://www.notion.com/product/notion-for-education",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "canva-ca",
    serviceName: "Canva Pro",
    aliases: ["canva", "canva pty", "canva com"],
    regularPriceMonthly: 16.99,
    studentPriceMonthly: 0,
    currency: "CAD",
    region: "CA",
    verificationMethod: "Education verification",
    offerUrl: "https://www.canva.com/education/students/",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "adobe-ca",
    serviceName: "Adobe Creative Cloud",
    aliases: ["adobe", "adobe inc", "adobe creative cloud"],
    regularPriceMonthly: 69.99,
    studentPriceMonthly: 25.99,
    currency: "CAD",
    region: "CA",
    verificationMethod: "Student verification",
    offerUrl: "https://www.adobe.com/ca/creativecloud/buy/students.html",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "amazon-prime-student-ca",
    serviceName: "Amazon Prime",
    aliases: ["amazon prime", "amzn prime", "prime video", "amazon digital"],
    regularPriceMonthly: 9.99,
    studentPriceMonthly: 4.99,
    currency: "CAD",
    region: "CA",
    verificationMethod: "Student email",
    offerUrl: "https://www.amazon.ca/prime/student",
    lastChecked: "2026-03-14",
    isActive: true,
  },
  {
    serviceId: "github-copilot-ca",
    serviceName: "GitHub Copilot Pro",
    aliases: ["github copilot", "copilot", "github", "github inc"],
    regularPriceMonthly: 10,
    studentPriceMonthly: 0,
    currency: "USD",
    region: "CA",
    verificationMethod: "GitHub Education verification",
    offerUrl: "https://github.com/features/copilot/plans",
    lastChecked: "2026-03-14",
    isActive: true,
  },
];
